scenario = "vectorBench"

dataStoreFeature = postgresql1
dataStoreMeta = hsqldb

# PostgreSQL direct connect settings
postgresHost = 127.0.0.1

numberOfThreads = 4
progressReportBase = 100
numberOfWarmUpIterations = 4

# Seeds
useRandomSeeds = true
randomSeedInsert = 46891971806236
randomSeedQuery = 196033374268

dimensionFeatureVectors = 100
batchSizeInserts = 2500
batchSizeQueries = 10

# Numbers of queries
numberOfEntries = 100000
numberOfSimpleKnnIntFeatureQueries = 0
numberOfSimpleKnnRealFeatureQueries = 0
numberOfSimpleMetadataQueries = 10
numberOfSimpleKnnIdIntFeatureQueries = 0
numberOfSimpleKnnIdRealFeatureQueries = 0
numberOfMetadataKnnIntFeatureQueries = 0
numberOfMetadataKnnRealFeatureQueries = 0
numberOfSimpleKnnRealCrossJoinQueries = 10
numberOfMetadataKnnRealCrossJoinQueries = 10
numberOfSimpleKnnRealFeatureFilteredQueries = 10
numberOfSimpleKnnBooleanFeatureFilteredQueries = 10
numberOfSimpleKnnBooleanFeatureQueries = 10


limitKnnQueries = 10
distanceNorm = COSINE
booleanDistanceNorm = HAMMING

