CREATE MATERIALIZED VIEW "user_materialized" AS SELECT * FROM "user" FRESHNESS MANUAL
CREATE MATERIALIZED VIEW "bid_materialized" AS SELECT * FROM "bid" FRESHNESS MANUAL
CREATE MATERIALIZED VIEW "picture_materialized" AS SELECT * FROM "picture" FRESHNESS MANUAL
CREATE MATERIALIZED VIEW "auction_materialized" AS SELECT * FROM "auction" FRESHNESS MANUAL
CREATE MATERIALIZED VIEW "category_materialized" AS SELECT * FROM "category" FRESHNESS MANUAL
CREATE MATERIALIZED VIEW "countAuction_materialized" AS SELECT count(*) as "NUMBER" FROM "auction" FRESHNESS MANUAL
CREATE MATERIALIZED VIEW "countBid_materialized" AS SELECT count(*) as "NUMBER" FROM "bid" FRESHNESS MANUAL
CREATE MATERIALIZED VIEW "auctionCategory_materialized" AS SELECT "id", "title", "category", "end_date" FROM "auction" FRESHNESS MANUAL
CREATE MATERIALIZED VIEW "topHundredSellerByNumberOfAuctions_materialized" AS SELECT u.last_name, u.first_name, count(a.id) as number FROM auction a INNER JOIN "user" u ON a."user" = u.id GROUP BY a."user", u.last_name, u.first_name ORDER BY number desc Limit 100 FRESHNESS MANUAL
CREATE MATERIALIZED VIEW "highestBid_materialized" AS SELECT "last_name", "first_name" FROM "user" WHERE "user"."id" = (SELECT highest.highestUser FROM (SELECT "bid"."user" as highestUser, MAX("bid"."amount") FROM "bid" GROUP BY "bid"."user" ORDER BY MAX("bid"."amount") DESC) as highest Limit 1) FRESHNESS MANUAL
CREATE MATERIALIZED VIEW "priceBetween_materialized" AS SELECT "auction"."title", "bid"."amount" FROM "auction", "bid" WHERE "bid"."auction" = "auction"."id" AND "bid"."amount" > 10 AND "bid"."amount" < 1000000 ORDER BY "bid"."amount" DESC Limit 100 FRESHNESS MANUAL
CREATE MATERIALIZED VIEW "otherInterestingActiveAuctions_materialized" SELECT c.last_name,a.title, a.end_date FROM (SELECT "public"."user"."last_name" as "last_name", "public"."user"."id" as "userid","public"."auction"."category" as "categoryid", "public"."auction"."condition" as "conditionid" FROM "public"."user","public"."auction" WHERE "public"."auction"."user" = "public"."user"."id" AND "public"."auction"."end_date" < CURRENT_TIMESTAMP Limit 1) as "c", "public"."auction" as "a" WHERE (c.categoryid = a.category AND c.conditionid = a."condition") AND a.end_date > CURRENT_TIMESTAMP Limit 100 FRESHNESS MANUAL
CREATE MATERIALIZED VIEW "differenceBetweenLowestAndHighestBid_materialized" SELECT difference, title, b.auctionid, c.auctionid FROM (SELECT (a.maxamount - a.minamount) as difference, a.auctionid as auctionid FROM (SELECT min("public"."bid"."amount") as "minamount", max("public"."bid"."amount") as "maxamount", "public"."bid"."auction" as "auctionid" FROM "public"."bid" WHERE "public"."bid"."auction" in ( SELECT "public"."auction"."id" FROM "public"."auction" ) Group by "public"."bid"."auction") as "a")as "b" join (SELECT "public"."auction"."title" as "title", "public"."auction"."id" as "auctionid" FROM "public"."auction") as "c" on b.auctionid = c.auctionid GROUP BY title, b.auctionid, c.auctionid, difference LIMIT 100 FRESHNESS MANUAL
CREATE MATERIALIZED VIEW "allActiveAuctions_materialized" SELECT "public"."auction"."title", "public"."auction"."end_date" FROM "public"."auction" WHERE "public"."auction"."end_date" > CURRENT_TIMESTAMP FRESHNESS MANUAL
CREATE MATERIALIZED VIEW "maxAmountConditionFinishedAuctions_materialized" SELECT b."maxamount", "d"."condition" FROM (SELECT a."maxamount", "c"."condition" FROM (SELECT max("public"."bid"."amount") as "maxamount", "public"."bid"."auction" as "auctionid" FROM "public"."bid" WHERE "public"."bid"."auction" in ( SELECT "public"."auction"."id" FROM "public"."auction" WHERE "end_date" < CURRENT_TIMESTAMP) Group by "public"."bid"."auction") as "a" INNER JOIN "public"."auction" as "c" ON a.auctionid = "c"."id") as "b" INNER JOIN "public"."condition" as "d" ON "b"."condition" = d."id" FRESHNESS MANUAL