CREATE TABLE "user" ( "id" integer NOT NULL, "email" varchar(100) NOT NULL, "password" varchar(100) NOT NULL, "last_name" varchar(50) NOT NULL, "first_name" varchar(50) NOT NULL, "gender" varchar(1) NOT NULL, "birthday" date NOT NULL, "city" varchar(50) NOT NULL, "zip_code" varchar(20) NOT NULL, "country" varchar(50) NOT NULL, primary key ("id") )
CREATE TABLE "bid" ( "id" integer NOT NULL, "amount" integer NOT NULL, "timestamp" timestamp  NOT NULL, "user" integer NOT NULL, "auction" integer NOT NULL, primary key ("id") )
CREATE TABLE "picture" ( "filename" varchar(50) NOT NULL, "type" varchar(20) NOT NULL, "size" integer NOT NULL, "auction" integer NOT NULL, primary key ("filename") )
CREATE TABLE "auction" ( "id" integer NOT NULL, "title" varchar(100) NOT NULL, "description" varchar(2500) NOT NULL, "start_date" timestamp  NOT NULL, "end_date" timestamp  NOT NULL, "category" integer NOT NULL, "user" integer NOT NULL, "condition" integer NOT NULL, primary key ("id") )
CREATE TABLE "category" ( "id" integer NOT NULL, "name" varchar(100) NOT NULL, primary key ("id") )
CREATE TABLE "condition" ("id" integer NOT NULL, "condition" varchar(100) NOT NULL, primary key ("id") )
ALTER TABLE "bid" ADD CONSTRAINT "fk_bid_user" FOREIGN KEY ( "user" ) REFERENCES "user"("id")
ALTER TABLE "bid" ADD CONSTRAINT "fk_bid_auction" FOREIGN KEY ( "auction" ) REFERENCES "auction"("id")
ALTER TABLE "picture" ADD CONSTRAINT "fk_picture_auction" FOREIGN KEY ( "auction" ) REFERENCES "auction"("id")
ALTER TABLE "auction" ADD CONSTRAINT "fk_auction_category" FOREIGN KEY ( "category" ) REFERENCES "category"("id")
ALTER TABLE "auction" ADD CONSTRAINT "fk_auction_user" FOREIGN KEY ( "user" ) REFERENCES "user"("id")
ALTER TABLE "auction" ADD CONSTRAINT "fk_auction_condition" FOREIGN KEY ( "condition" ) REFERENCES "condition"("id")