CREATE VIEW "user_materialized" AS SELECT * FROM "user" FRESHNESS INTERVAL 10 "min"
CREATE VIEW "bid_materialized" AS SELECT * FROM "bid" FRESHNESS INTERVAL 10 "min"
CREATE VIEW "picture_materialized" AS SELECT * FROM "picture" FRESHNESS INTERVAL 10 "min"
CREATE VIEW "auction_materialized" AS SELECT * FROM "auction" FRESHNESS INTERVAL 10 "min"
CREATE VIEW "category_materialized" AS SELECT * FROM "category" FRESHNESS INTERVAL 10 "min"
CREATE VIEW "countAuction_materialized" AS SELECT count(*) as "NUMBER" FROM "auction" FRESHNESS INTERVAL 10 "min"
CREATE VIEW "countBid_materialized" AS SELECT count(*) as "NUMBER" FROM "bid" FRESHNESS INTERVAL 10 "min"
CREATE VIEW "auctionCategory_materialized" AS SELECT "id", "title", "end_date" FROM "auction" ORDER BY "end_date" desc FRESHNESS INTERVAL 10 "min"