CREATE VIEW "user_view" AS SELECT * FROM "user"
CREATE VIEW "bid_view" AS SELECT * FROM "bid"
CREATE VIEW "picture_view" AS SELECT * FROM "picture"
CREATE VIEW "auction_view" AS SELECT * FROM "auction"
CREATE VIEW "category_view" AS SELECT * FROM "category"
CREATE VIEW "countAuction" AS SELECT count(*) as "NUMBER" FROM "auction"
CREATE VIEW "countBid" AS SELECT count(*) as "NUMBER" FROM "bid"
CREATE VIEW "auctionCategory_view" AS SELECT "id", "title", "end_date", "category" FROM "auction"